# Generated by Django 4.1.4 on 2023-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='index_image')),
                ('background', models.ImageField(blank=True, null=True, upload_to='index_image')),
                ('team', models.CharField(blank=True, max_length=50, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='index_image')),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('description1', models.CharField(blank=True, max_length=300, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='index_image')),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('description2', models.CharField(blank=True, max_length=300, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='index_image')),
                ('title3', models.CharField(blank=True, max_length=50, null=True)),
                ('description3', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
