# Generated by Django 4.1.4 on 2023-02-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexchange',
            name='cond',
            field=models.BooleanField(default=False),
        ),
    ]
