# Generated by Django 4.1.4 on 2023-02-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_indexchange_cond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexchange',
            name='icon',
        ),
    ]
