# Generated by Django 4.1.4 on 2023-02-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_indexchange_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexchange',
            name='cond',
        ),
    ]
