# Generated by Django 4.1.4 on 2023-02-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_indexchange_cond'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexchange',
            options={'verbose_name': 'Modificacion', 'verbose_name_plural': 'Modificaciones'},
        ),
        migrations.AlterField(
            model_name='indexchange',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='index_image', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='indexchange',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo de equipo'),
        ),
        migrations.AlterField(
            model_name='indexchange',
            name='title1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Persona 1'),
        ),
        migrations.AlterField(
            model_name='indexchange',
            name='title2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Persona 2'),
        ),
        migrations.AlterField(
            model_name='indexchange',
            name='title3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Persona 3'),
        ),
    ]
