# Generated by Django 4.1.4 on 2023-02-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('environments', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('area', models.FloatField()),
                ('sold', models.BooleanField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='sales_image')),
            ],
        ),
    ]
