# Generated by Django 4.1.4 on 2023-02-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='profile_image',
            new_name='sale_image',
        ),
    ]
