# Generated by Django 4.1.4 on 2023-02-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='environments',
            field=models.IntegerField(verbose_name='Ambientes'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_image',
            field=models.ImageField(blank=True, null=True, upload_to='sales_image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold',
            field=models.BooleanField(verbose_name='Vendido'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titutlo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='toilets',
            field=models.IntegerField(verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='zone',
            field=models.CharField(max_length=35, verbose_name='Zona'),
        ),
    ]
